[2023-12-21T13:23:10.560+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:21:00.607777+00:00/task_id=process_messages permission to 509
[2023-12-21T13:23:10.589+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:21:00.607777+00:00/task_id=process_messages permission to 509
[2023-12-21T13:23:10.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:21:00.607777+00:00 [queued]>
[2023-12-21T13:23:10.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:21:00.607777+00:00 [queued]>
[2023-12-21T13:23:10.631+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-12-21T13:23:10.642+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_messages> on 2023-12-21 13:21:00.607777+00:00
[2023-12-21T13:23:10.646+0000] {standard_task_runner.py:57} INFO - Started process 4768 to run task
[2023-12-21T13:23:10.649+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pubsub_pandas_dag', 'process_messages', 'manual__2023-12-21T13:21:00.607777+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/process_pubsub_message.py', '--cfg-path', '/tmp/tmpsl9sg447']
[2023-12-21T13:23:10.651+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask process_messages
[2023-12-21T13:23:10.665+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-21T13:23:10.693+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:21:00.607777+00:00/task_id=process_messages permission to 509
[2023-12-21T13:23:10.701+0000] {task_command.py:416} INFO - Running <TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:21:00.607777+00:00 [running]> on host 491e3d3d49e0
[2023-12-21T13:23:10.759+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pubsub_pandas_dag' AIRFLOW_CTX_TASK_ID='process_messages' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T13:21:00.607777+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T13:21:00.607777+00:00'
[2023-12-21T13:23:10.760+0000] {logging_mixin.py:154} INFO - Hello
[2023-12-21T13:23:10.762+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_pubsub_message.py", line 63, in process_messages_with_pandas
    messages = ti.xcom_pull(task_ids='retrieve_messages', key='messages')
NameError: name 'ti' is not defined
[2023-12-21T13:23:10.770+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pubsub_pandas_dag, task_id=process_messages, execution_date=20231221T132100, start_date=20231221T132310, end_date=20231221T132310
[2023-12-21T13:23:10.780+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task process_messages (name 'ti' is not defined; 4768)
[2023-12-21T13:23:10.822+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T13:23:10.836+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
