[2023-12-02T00:51:38.246+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [queued]>
[2023-12-02T00:51:38.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [queued]>
[2023-12-02T00:51:38.254+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-02T00:51:38.265+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_messages> on 2023-12-02 00:46:35.916235+00:00
[2023-12-02T00:51:38.270+0000] {standard_task_runner.py:57} INFO - Started process 845 to run task
[2023-12-02T00:51:38.273+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pubsub_pandas_dag', 'retrieve_messages', 'manual__2023-12-02T00:46:35.916235+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/process_pubsub_message.py', '--cfg-path', '/tmp/tmpz9q2gvm7']
[2023-12-02T00:51:38.275+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_messages
[2023-12-02T00:51:38.286+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-02T00:51:38.320+0000] {task_command.py:416} INFO - Running <TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [running]> on host 2fdb813c544a
[2023-12-02T00:51:38.380+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pubsub_pandas_dag' AIRFLOW_CTX_TASK_ID='retrieve_messages' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:46:35.916235+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T00:46:35.916235+00:00'
[2023-12-02T00:51:38.382+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_pubsub_message.py", line 15, in retrieve_pubsub_messages_to_xcom
    credentials = service_account.Credentials.from_service_account_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 260, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/credentials.json'
[2023-12-02T00:51:38.392+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pubsub_pandas_dag, task_id=retrieve_messages, execution_date=20231202T004635, start_date=20231202T005138, end_date=20231202T005138
[2023-12-02T00:51:38.401+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task retrieve_messages ([Errno 2] No such file or directory: '/credentials.json'; 845)
[2023-12-02T00:51:38.445+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T00:51:38.464+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
