[2023-12-02T00:46:37.062+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [queued]>
[2023-12-02T00:46:37.069+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [queued]>
[2023-12-02T00:46:37.069+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-02T00:46:37.080+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_messages> on 2023-12-02 00:46:35.916235+00:00
[2023-12-02T00:46:37.083+0000] {standard_task_runner.py:57} INFO - Started process 552 to run task
[2023-12-02T00:46:37.085+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pubsub_pandas_dag', 'retrieve_messages', 'manual__2023-12-02T00:46:35.916235+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/process_pubsub_message.py', '--cfg-path', '/tmp/tmp2m7g490y']
[2023-12-02T00:46:37.087+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask retrieve_messages
[2023-12-02T00:46:37.102+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-02T00:46:37.134+0000] {task_command.py:416} INFO - Running <TaskInstance: pubsub_pandas_dag.retrieve_messages manual__2023-12-02T00:46:35.916235+00:00 [running]> on host 2fdb813c544a
[2023-12-02T00:46:37.194+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pubsub_pandas_dag' AIRFLOW_CTX_TASK_ID='retrieve_messages' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:46:35.916235+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T00:46:35.916235+00:00'
[2023-12-02T00:46:37.196+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_pubsub_message.py", line 12, in retrieve_pubsub_messages_to_xcom
    path = os.environ['AIRFLOW_PROJ_DIR']
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AIRFLOW_PROJ_DIR'
[2023-12-02T00:46:37.208+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pubsub_pandas_dag, task_id=retrieve_messages, execution_date=20231202T004635, start_date=20231202T004637, end_date=20231202T004637
[2023-12-02T00:46:37.217+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task retrieve_messages ('AIRFLOW_PROJ_DIR'; 552)
[2023-12-02T00:46:37.261+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T00:46:37.281+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
