[2023-12-01T23:04:31.952+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: advanced_dag.task2 manual__2023-12-01T22:49:27.286301+00:00 [queued]>
[2023-12-01T23:04:31.961+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: advanced_dag.task2 manual__2023-12-01T22:49:27.286301+00:00 [queued]>
[2023-12-01T23:04:31.962+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-01T23:04:31.973+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task2> on 2023-12-01 22:49:27.286301+00:00
[2023-12-01T23:04:31.976+0000] {standard_task_runner.py:57} INFO - Started process 700 to run task
[2023-12-01T23:04:31.978+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'advanced_dag', 'task2', 'manual__2023-12-01T22:49:27.286301+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp8j75h1pl']
[2023-12-01T23:04:31.980+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask task2
[2023-12-01T23:04:32.013+0000] {task_command.py:416} INFO - Running <TaskInstance: advanced_dag.task2 manual__2023-12-01T22:49:27.286301+00:00 [running]> on host cbfe888ad84e
[2023-12-01T23:04:32.065+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='advanced_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T22:49:27.286301+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T22:49:27.286301+00:00'
[2023-12-01T23:04:32.066+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T23:04:32.067+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-12-01T23:04:32.072+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T23:04:32.074+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-01T23:04:32.082+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-01T23:04:32.085+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=advanced_dag, task_id=task2, execution_date=20231201T224927, start_date=20231201T230431, end_date=20231201T230432
[2023-12-01T23:04:32.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 700)
[2023-12-01T23:04:32.110+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T23:04:32.127+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
