[2023-12-01T22:57:47.070+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: advanced_dag.task2 manual__2023-12-01T22:47:43.578985+00:00 [queued]>
[2023-12-01T22:57:47.077+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: advanced_dag.task2 manual__2023-12-01T22:47:43.578985+00:00 [queued]>
[2023-12-01T22:57:47.077+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2023-12-01T22:57:47.089+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task2> on 2023-12-01 22:47:43.578985+00:00
[2023-12-01T22:57:47.092+0000] {standard_task_runner.py:57} INFO - Started process 522 to run task
[2023-12-01T22:57:47.094+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'advanced_dag', 'task2', 'manual__2023-12-01T22:47:43.578985+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpz_h00tsv']
[2023-12-01T22:57:47.096+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask task2
[2023-12-01T22:57:47.129+0000] {task_command.py:416} INFO - Running <TaskInstance: advanced_dag.task2 manual__2023-12-01T22:47:43.578985+00:00 [running]> on host cbfe888ad84e
[2023-12-01T22:57:47.185+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='advanced_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T22:47:43.578985+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T22:47:43.578985+00:00'
[2023-12-01T22:57:47.186+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T22:57:47.187+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-12-01T22:57:47.193+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T22:57:47.195+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-01T22:57:47.203+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-01T22:57:47.206+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=advanced_dag, task_id=task2, execution_date=20231201T224743, start_date=20231201T225747, end_date=20231201T225747
[2023-12-01T22:57:47.217+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 522)
[2023-12-01T22:57:47.226+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T22:57:47.242+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
