[2023-12-21T13:20:29.709+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:15:23.494016+00:00/task_id=process_messages permission to 509
[2023-12-21T13:20:29.740+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:15:23.494016+00:00/task_id=process_messages permission to 509
[2023-12-21T13:20:29.774+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:15:23.494016+00:00 [queued]>
[2023-12-21T13:20:29.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:15:23.494016+00:00 [queued]>
[2023-12-21T13:20:29.783+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-21T13:20:29.793+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_messages> on 2023-12-21 13:15:23.494016+00:00
[2023-12-21T13:20:29.797+0000] {standard_task_runner.py:57} INFO - Started process 4588 to run task
[2023-12-21T13:20:29.800+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pubsub_pandas_dag', 'process_messages', 'manual__2023-12-21T13:15:23.494016+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/process_pubsub_message.py', '--cfg-path', '/tmp/tmp53m1hdwk']
[2023-12-21T13:20:29.802+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask process_messages
[2023-12-21T13:20:29.815+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-21T13:20:29.843+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=pubsub_pandas_dag/run_id=manual__2023-12-21T13:15:23.494016+00:00/task_id=process_messages permission to 509
[2023-12-21T13:20:29.851+0000] {task_command.py:416} INFO - Running <TaskInstance: pubsub_pandas_dag.process_messages manual__2023-12-21T13:15:23.494016+00:00 [running]> on host 491e3d3d49e0
[2023-12-21T13:20:29.910+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pubsub_pandas_dag' AIRFLOW_CTX_TASK_ID='process_messages' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T13:15:23.494016+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T13:15:23.494016+00:00'
[2023-12-21T13:20:29.912+0000] {logging_mixin.py:154} INFO - Hello
[2023-12-21T13:20:29.912+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_pubsub_message.py", line 63, in process_messages_with_pandas
    messages = ti.xcom_pull(task_ids='retrieve_messages', key='messages')
NameError: name 'ti' is not defined
[2023-12-21T13:20:29.921+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pubsub_pandas_dag, task_id=process_messages, execution_date=20231221T131523, start_date=20231221T132029, end_date=20231221T132029
[2023-12-21T13:20:29.931+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task process_messages (name 'ti' is not defined; 4588)
[2023-12-21T13:20:29.973+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T13:20:29.987+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
